all:
  children:
    app_servers:
      hosts:
        app-server:
          ansible_host: 34.186.24.52
          gcp_project: "skillbox-devops-basic"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    gitlab:
      hosts:
        gitlab-server:
          ansible_host: 34.50.169.169
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    prometheus:
      hosts:
        prometheus-vm:
          ansible_host: 34.125.163.11
          ansible_user: ubuntu

    grafana:
      hosts:
        grafana-vm:
          ansible_host: 34.16.186.65
          ansible_user: ubuntu
      vars:
        grafana_admin_user: admin
        grafana_admin_password: 123456
        grafana_domain: grafana.avtostrada.kz
