all:
  children:
    app_servers:
      hosts:
        app-server-prod:
          ansible_host: 34.16.171.67
          internal_ip: 10.0.1.9
          gcp_project: "skillbox-devops-basic"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
        app-server-stage:
          ansible_host: 34.125.205.177
          internal_ip: 10.0.1.10
          gcp_project: "skillbox-devops-basic"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3

      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    gitlab:
      hosts:
        gitlab-server:
          ansible_host: 34.50.169.169
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    prometheus:
      hosts:
        prometheus-vm:
          ansible_host: 34.125.163.11
          internal_ip: 10.0.1.7
          ansible_user: ubuntu

    grafana:
      hosts:
        grafana-vm:
          ansible_host: 34.16.186.65
          internal_ip: 10.0.1.8
          ansible_user: ubuntu
      vars:
        grafana_admin_user: admin
        grafana_admin_password: 123456
        grafana_domain: grafana.avtostrada.kz
        app_instances:
          - "app-server-prod"
          - "app-server-stage"
