---
- name: Install GitLab CE and GitLab Runner
  hosts: gitlab
  become: true
  vars:
    external_url: "http://ci.avtostrada.kz"
  tasks:
    - name: Install dependencies
      apt:
        name: ['curl', 'ca-certificates', 'apt-transport-https', 'software-properties-common']
        state: present
        update_cache: yes

    - name: Add GitLab repo
      shell: |
        curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | bash

    - name: Install GitLab CE
      apt:
        name: gitlab-ce
        state: present

    - name: Configure GitLab external URL
      lineinfile:
        path: /etc/gitlab/gitlab.rb
        regexp: "^external_url"
        line: "external_url '{{ external_url }}'"

    - name: Reconfigure GitLab
      command: gitlab-ctl reconfigure

    - name: Install GitLab Runner
      apt:
        name: gitlab-runner
        state: present
        update_cache: yes

